POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZDBjYmYwOTY4YmE4NzYwMGY4OTI3NSIsImlhdCI6MTY3NDYzMjg2Mn0.sTkyi_kCb-6_CwI34RaJ_qRmEgEJiAmGv2Uum4rkzAY

{
    "title": "Meika",
    "author": "Poika",
    "url": "youtube",
    "likes": "2"
}